# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(choices=[(1, b'SuperAdmin'), (2, b'UserAdmin'), (3, b'UserEmployee')], default=0),
        ),
    ]
