# Generated by Django 2.0.2 on 2018-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180204_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'SuperAdmin'), (2, 'UserAdmin'), (3, 'UserEmployee')], default=0),
        ),
    ]
