# Generated by Django 2.0.2 on 2018-02-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180220_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facepath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
