# Generated by Django 2.0.2 on 2018-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_detail',
            name='floor',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
