# Generated by Django 2.0.2 on 2018-03-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_camera_detail_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_detail',
            name='floor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
