# Generated by Django 2.0.2 on 2018-03-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20180321_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_detail',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='camera_detail',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=25),
        ),
    ]
