# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searching_detail',
            name='ShirtColorB',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searching_detail',
            name='ShirtColorG',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searching_detail',
            name='ShirtColorR',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
