# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20180204_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searching_detail',
            name='facepath',
            field=models.ImageField(null=True, upload_to='face/'),
        ),
    ]
