# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20180205_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searching_detail',
            old_name='facepath',
            new_name='face_image',
        ),
    ]
