# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_auto_20180205_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searching_detail',
            name='face_image',
        ),
        migrations.AddField(
            model_name='searching_detail',
            name='face_path',
            field=models.ImageField(max_length=200, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='searching_detail',
            name='fullbody_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
