# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20180220_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searching_detail',
            name='face_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
