# Generated by Django 2.0.2 on 2018-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_auto_20180220_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='searching_detail',
            name='recognition_face',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
