# Generated by Django 2.0.2 on 2018-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_searching_detail_recognition_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searching_detail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
