# Generated by Django 2.0.2 on 2018-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_auto_20180308_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searching_detail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
