# Generated by Django 2.0.2 on 2018-03-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_searching_detail_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searching_detail',
            old_name='videopath',
            new_name='video_path',
        ),
    ]
